services:
  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    container_name: resume_pipeline_web
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/web/.env
    networks:
      - dev-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=dev-net
      - traefik.http.services.cv.loadbalancer.server.port=3000
      - traefik.http.routers.cv.rule=Host(`cv.localhost`)
      - traefik.http.routers.cv.entrypoints=https
      - traefik.http.routers.cv.tls=true
      - traefik.http.routers.cv-http.rule=Host(`cv.localhost`)
      - traefik.http.routers.cv-http.entrypoints=http
      - traefik.http.routers.cv-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    depends_on:
      api:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: infra/docker/api.dev.Dockerfile
    container_name: resume_pipeline_api
    platform: linux/amd64 # Patch for M1 Mac
    env_file:
      - ./apps/api/.env
    networks:
      - dev-net
    volumes:
      - ./apps/api/:/app
      - /app/.venv/
      - uv-cache:/root/.cache/uv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.docker.network=dev-net
      - traefik.http.services.cva.loadbalancer.server.port=8000
      - traefik.http.routers.cva.rule=Host(`cva.localhost`)
      - traefik.http.routers.cva.entrypoints=https
      - traefik.http.routers.cva.tls=true
      - traefik.http.routers.cva-http.rule=Host(`cva.localhost`)
      - traefik.http.routers.cva-http.entrypoints=http
      - traefik.http.routers.cva-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

  api-prod-test:
    profiles:
      - test # This hides the service from standard "docker compose up" commands
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: resume_pipeline_api_prod
    ports:
      - "40003:8000"
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379/0
    networks:
      - dev-net

networks:
  dev-net:
    external: true

volumes:
  uv-cache: